# Generated by Django 3.2.20 on 2023-08-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
